# Generated by Django 5.1 on 2024-08-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
