# Generated by Django 5.1 on 2024-08-23 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chosen_vote_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
